Config = {}

-- CRAFT DE ARMAS E ACESSORIOS~
Config.RequiredJob = true
Config.GangsArmas = {"ballas", "soa" } 
Config.GangsAccessorios = {"ballas", "bloods"} 

Config.CraftAcessorios = vector3(1535.07, 3585.3, 38.77)
Config.CraftArmas = vector3(1533.51, 3588.24, 38.77)

Config.VendingObjects = {
    "prop_vend_soda_01",
    "prop_vend_soda_02",
    "prop_vend_water_01"
}

Config.BinObjects = {
    "prop_bin_05a",
}

Config.CraftingObject = "prop_toolchest_05" -- Only needed if not using target | Line 928 to change Target Models

Config.VendingItem = {
    [1] = {
        name = "kurkakola",
        price = 4,
        amount = 50,
        info = {},
        type = "item",
        slot = 1,
    },
    [2] = {
        name = "water_bottle",
        price = 4,
        amount = 50,
        info = {},
        type = "item",
        slot = 2,
    },
}


Config.CraftingItems = {
    [1] = {
        name = "weapon_snspistol",
        amount = 50,
        info = {},
        costs = {
            ["snspistol_defaultclip"] = 1,
            ["snspistol_extendedclip"] = 1,
            ["snspistol_grip"] = 1,
            ["pistol_suppressor"] = 1,
            ["pistol_flashlight"] = 1,
            ["pecadearma"] = 3,
        },
        type = "weapon",
        slot = 1,
        threshold = 0,
        points = 1,
    },
    [2] = {
        name = "weapon_pistol",
        amount = 50,
        info = {},
        costs = {
            ["pistol_defaultclip"] = 1,
            ["pistol_extendedclip"] = 1,
            ["pistol_flashlight"] = 1,
            ["pistol_suppressor"] = 1,
            ["pecadearma"] = 6,
        },
        type = "item",
        slot = 2,
        threshold = 0,
        points = 1,
    },
    [3] = {
        name = "weapon_machinepistol",
        amount = 50,
        info = {},
        costs = {
            ["machinepistol_defaultclip"] = 1,
            ["machinepistol_extendedclip"] = 1,
            ["machinepistol_drum"] = 1,
            ["pistol_suppressor"] = 1,
            ["pistol_flashlight"] = 1,
            ["pecadearma"] = 7,
        },
        type = "item",
        slot = 3,
        threshold = 0,
        points = 1,
    },
    [4] = {
        name = "weapon_microsmg",
        amount = 50,
        info = {},
        costs = {
            ["microsmg_defaultclip"] = 1,
            ["microsmg_extendedclip"] = 1,
            ["microsmg_scope"] = 1,
            ["pecadearma"] = 10,
        },
        type = "item",
        slot = 4,
        threshold = 0,
        points = 1,
    },
    [5] = {
        name = "weapon_pistol50",
        amount = 50,
        info = {},
        costs = {
            ["pistol50_defaultclip"] = 1,
            ["pistol50_extendedclip"] = 1,
            ["pistol_suppressor"] = 1,
            ["pistol_flashlight"] = 1,
            ["pecadearma"] = 13,
        },
        type = "item",
        slot = 5,
        threshold = 0,
        points = 1,
    },
    [6] = {
        name = "weapon_gusenberg",
        amount = 50,
        info = {},
        costs = {
            ["gusenberg_defaultclip"] = 1,
            ["gusenberg_extendedclip"] = 1,
            ["rifle_flashlight"] = 1,
            ["rifle_grip"] = 1,
            ["rifle_suppressor"] = 1,
            ["pecadearma"] = 16,
        },
        type = "item",
        slot = 6,
        threshold = 0,
        points = 1,
    },
    [7] = {
        name = "weapon_compactrifle",
        amount = 50,
        info = {},
        costs = {
            ["compactrifle_defaultclip"] = 1,
            ["compactrifle_extendedclip"] = 1,
            ["compactrifle_drum"] = 1,
            ["rifle_grip"] = 1,
            ["rifle_suppressor"] = 1,
            ["pecadearma"] = 18,
        },
        type = "item",
        slot = 7,
        threshold = 0,
        points = 1,
    },
    [8] = {
        name = "weapon_assaultrifle",
        amount = 50,
        info = {},
        costs = {
            ["assaultrifle_defaultclip"] = 1,
            ["assaultrifle_extendedclip"] = 1,
            ["assaultrifle_drum"] = 1,
            ["rifle_grip"] = 1,
            ["rifle_suppressor"] = 1,
            ["rifle_flashlight"] = 1,
            ["pecadearma"] = 25,
        },
        type = "item",
        slot = 8,
        threshold = 0,
        points = 1,
    },
    [9] = {
        name = "weapon_assaultshotgun",
        amount = 50,
        info = {},
        costs = {
            ["assaultshotgun_defaultclip"] = 1,
            ["assaultshotgun_extendedclip"] = 1,
            ["shotgun_suppressor"] = 1,
            ["pecadearma"] = 30,
        },
        type = "item",
        slot = 9,
        threshold = 0,
        points = 1,
    },
    [10] = {
        name = "weapon_bullpuprifle",
        amount = 50,
        info = {},
        costs = {
            ["bullpuprifle_defaultclip"] = 1,
            ["bullpuprifle_extendedclip"] = 1,
            ["rifle_grip"] = 1,
            ["rifle_suppressor"] = 1,
            ["rifle_flashlight"] = 1,
            ["pecadearma"] = 32,
        },
        type = "item",
        slot = 10,
        threshold = 0,
        points = 1,
    },
}

Config.AttachmentCrafting = {
    ["items"] = {
        [1] = {
            name = "handcuffs",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 100,
                ["plastic"] = 50,
            },
            type = "item",
            slot = 1,
            threshold = 0,
            points = 1,
        },
        [2] = {
            name = "armor",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 30,
                ["plastic"] = 50,
                ["rubber"] = 250,
            },
            type = "item",
            slot = 2,
            threshold = 0,
        points = 1,
        },
        [3] = {
            name = "heavyarmor",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 60,
                ["plastic"] = 100,
                ["rubber"] = 500,
            },
            type = "item",
            slot = 3,
            threshold = 0,
            points = 1,
        },
        --PISTOLS
        [4] = {
            name = "pistol_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 25,
                ["plastic"] = 25,
            },
            type = "item",
            slot = 4,
            threshold = 0,
            points = 1,
        },
        [5] = {
            name = "pistol_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 25,
                ["plastic"] = 25,
            },
            type = "item",
            slot = 5,
            threshold = 0,
            points = 1,
        },
        [6] = {
            name = "pistol_flashlight",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 25,
                ["plastic"] = 25,
            },
            type = "item",
            slot = 6,
            threshold = 0,
            points = 1,
        },
        [7] = {
            name = "pistol_suppressor",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 25,
                ["plastic"] = 25,
            },
            type = "item",
            slot = 7,
            threshold = 0,
            points = 1,
        },
        [8] = {
            name = "combatpistol_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 100,
                ["plastic"] = 50,
            },
            type = "item",
            slot = 8,
            threshold = 0,
            points = 1,
        },
        [9] = {
            name = "combatpistol_extendedclip", 
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 100,
                ["plastic"] = 50,
            },
            type = "item",
            slot = 9,
            threshold = 0,
            points = 1,
        },
        [10] = {
            name = "pistol50_defaultclip",
            amount = 50,
            info = {},
            costs = {
                ["metalscrap"] = 100,
                ["plastic"] = 50,
            },
            type = "item",
            slot = 10,
            threshold = 0,
            points = 1,
        },
        [11] = {
            name = "pistol50_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 100,
                ["plastic"] = 50,
            },
            type = "item",
            slot = 11,
            threshold = 0,
            points = 1,
        },
        [12] = {
            name = "snspistol_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 25,
                ["plastic"] = 25,
            },
            type = "item",
            slot = 12,
            threshold = 0,
            points = 1,
        },
        [13] = {
            name = "snspistol_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 25,
                ["plastic"] = 25,
            },
            type = "item",
            slot = 13,
            threshold = 0,
            points = 1,
        },
        [14] = {
            name = "snspistol_grip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 25,
                ["plastic"] = 25,
            },
            type = "item",
            slot = 14,
            threshold = 0,
            points = 1,
        },
        -- SMG
        [15] = {
            name = "smg_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 15,
            threshold = 0,
            points = 1,
        },
        [16] = {
            name = "smg_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 16,
            threshold = 0,
            points = 1,
        },
        [17] = {
            name = "smg_drum",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 17,
            threshold = 0,
            points = 1,
        },
        [18] = {
            name = "smg_scope",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 18,
            threshold = 0,
            points = 1,
        },
        [19] = {
            name = "microsmg_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 19,
            threshold = 0,
            points = 1,
        },
        [20] = {
            name = "microsmg_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 20,
            threshold = 0,
            points = 1,
        },
        [21] = {
            name = "microsmg_scope",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 21,
            threshold = 0,
            points = 1,
        },
        [22] = {
            name = "machinepistol_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 50,
            },
            type = "item",
            slot = 22,
            threshold = 0,
            points = 1,
        },
        [23] = {
            name = "machinepistol_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 50,
            },
            type = "item",
            slot = 23,
            threshold = 0,
            points = 1,
        },
        [24] = {
            name = "machinepistol_drum",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 50,
            },
            type = "item",
            slot = 24,
            threshold = 0,
            points = 1,
        },
        -- SHOTGUNS
        [25] = {
            name = "assaultshotgun_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 200,
                ["plastic"] = 150,
            },
            type = "item",
            slot = 25,
            threshold = 0,
            points = 1,
        },
        [26] = {
            name = "assaultshotgun_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 200,
                ["plastic"] = 150,
            },
            type = "item",
            slot = 26,
            threshold = 0,
            points = 1,
        },
        [27] = {
            name = "shotgun_suppressor",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 100,
                ["plastic"] = 150,
            },
            type = "item",
            slot = 27,
            threshold = 0,
            points = 1,
        },
        -- RIFLES
        [28] = {
            name = "assaultrifle_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 175,
                ["plastic"] = 175,
            },
            type = "item",
            slot = 28,
            threshold = 0,
            points = 1,
        },
        [29] = {
            name = "assaultrifle_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 175,
                ["plastic"] = 175,
            },
            type = "item",
            slot = 29,
            threshold = 0,
            points = 1,
        },
        [30] = {
            name = "assaultrifle_drum",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 175,
                ["plastic"] = 175,
            },
            type = "item",
            slot = 30,
            threshold = 0,
            points = 1,
        },
        [31] = {
            name = "rifle_flashlight",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 150,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 31,
            threshold = 0,
            points = 1,
        },
        [32] = {
            name = "rifle_grip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 150,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 32,
            threshold = 0,
            points = 1,
        },
        [33] = {
            name = "rifle_suppressor",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 50,
                ["plastic"] = 200,
            },
            type = "item",
            slot = 33,
            threshold = 0,
            points = 1,
        },
        [34] = {
            name = "carbinerifle_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 175,
                ["plastic"] = 175,
            },
            type = "item",
            slot = 34,
            threshold = 0,
            points = 1,
        },
        [35] = {
            name = "carbinerifle_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 175,
                ["plastic"] = 175,
            },
            type = "item",
            slot = 35,
            threshold = 0,
            points = 1,
        },
        [36] = {
            name = "carbinerifle_scope",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 175,
                ["plastic"] = 175,
            },
            type = "item",
            slot = 36,
            threshold = 0,
            points = 1,
        },
        [37] = {
            name = "bullpuprifle_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 175,
                ["plastic"] = 175,
            },
            type = "item",
            slot = 37,
            threshold = 0,
            points = 1,
        },
        [38] = {
            name = "bullpuprifle_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 175,
                ["plastic"] = 175,
            },
            type = "item",
            slot = 38,
            threshold = 0,
            points = 1,
        },
        [39] = {
            name = "compactrifle_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 150,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 39,
            threshold = 0,
            points = 1,
        },
        [40] = {
            name = "compactrifle_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 150,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 40,
            threshold = 0,
            points = 1,
        },
        [41] = {
            name = "compactrifle_drum",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 150,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 41,
            threshold = 0,
            points = 1,
        },
        [42] = {
            name = "gusenberg_defaultclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 100,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 42,
            threshold = 0,
            points = 1,
        },
        [43] = {
            name = "gusenberg_extendedclip",
            amount = 1,
            info = {},
            costs = {
                ["metalscrap"] = 100,
                ["plastic"] = 100,
            },
            type = "item",
            slot = 43,
            threshold = 0,
            points = 1,
        },

    }
}

MaxInventorySlots = 41

BackEngineVehicles = {
    [`ninef`] = true,
    [`adder`] = true,
    [`vagner`] = true,
    [`t20`] = true,
    [`infernus`] = true,
    [`zentorno`] = true,
    [`reaper`] = true,
    [`comet2`] = true,
    [`comet3`] = true,
    [`jester`] = true,
    [`jester2`] = true,
    [`cheetah`] = true,
    [`cheetah2`] = true,
    [`prototipo`] = true,
    [`turismor`] = true,
    [`pfister811`] = true,
    [`ardent`] = true,
    [`nero`] = true,
    [`nero2`] = true,
    [`tempesta`] = true,
    [`vacca`] = true,
    [`bullet`] = true,
    [`osiris`] = true,
    [`entityxf`] = true,
    [`turismo2`] = true,
    [`fmj`] = true,
    [`re7b`] = true,
    [`tyrus`] = true,
    [`italigtb`] = true,
    [`penetrator`] = true,
    [`monroe`] = true,
    [`ninef2`] = true,
    [`stingergt`] = true,
    [`surfer`] = true,
    [`surfer2`] = true,
    [`gp1`] = true,
    [`autarch`] = true,
    [`tyrant`] = true
}

Config.MaximumAmmoValues = {
    ["pistol"] = 250,
    ["smg"] = 250,
    ["shotgun"] = 200,
    ["rifle"] = 250,
}