
Citizen.CreateThread(function()
    -- CATEGORIAS
    AddTextEntry("bmw", "BMW")
    AddTextEntry("alfa", "Alfa Romeo")
    AddTextEntry("aston", "Aston Martin")
    AddTextEntry("audi", "Audi")
    AddTextEntry("bentley", "Bentley")
    AddTextEntry("bicicletas", "bicicletas")
    AddTextEntry("bugatti", "Bugatti")
    AddTextEntry("chevrolet", "Chevrolet")
    AddTextEntry("citroen", "Citroen")
    AddTextEntry("dodge", "Dodge")
    AddTextEntry("ferrari", "Ferrari")
    AddTextEntry("fiat", "Fiat")
    AddTextEntry("ford", "Ford")
    AddTextEntry("harley", "Harley")
    AddTextEntry("Honda", "Honda")
    AddTextEntry("jaguar", "Jaguar")
    AddTextEntry("kawasaki", "Kawasaki")
    AddTextEntry("koenigsegg", "Koenigsegg")
    AddTextEntry("ktm", "KTM")
    AddTextEntry("lamborghini", "Lamborghini")
    AddTextEntry("maserati", "Maserati")
    AddTextEntry("mazda", "Mazda")
    AddTextEntry("mclaren", "Mclaren")
    AddTextEntry("mercedes", "Mercedes")
    AddTextEntry("mini", "Mini")
    AddTextEntry("mitsubishi", "Mitsubishi")
    AddTextEntry("nissan", "Nissan")
    AddTextEntry("opel", "Opel")
    AddTextEntry("peugeot", "Peugeot")
    AddTextEntry("porsche", "Porsche")
    AddTextEntry("rangerover", "Range Rover")
    AddTextEntry("renault", "Renault")
    AddTextEntry("rollsroyce", "Rolls Royce")
    AddTextEntry("seat", "Seat")
    AddTextEntry("skoda", "Skoda")
    AddTextEntry("subaru", "Subaru")
    AddTextEntry("suzuki", "Suzuki")
    AddTextEntry("tesla", "Tesla")
    AddTextEntry("toyota", "Toyota")
    AddTextEntry("utility", "Utilidades")
    AddTextEntry("vip", "VIP")
    AddTextEntry("volkswagen", "Volkswagen")
    AddTextEntry("volvo", "Volvo")
    AddTextEntry("yamaha", "Yamaha")
    AddTextEntry("ducati", "Ducati")
    AddTextEntry("jeep", "Jeep")


    -- CARROS
    AddTextEntry("polo2018", "Volkswagen Polo R-line 2018")
    AddTextEntry("blista", "Audi A3 1999")
    AddTextEntry("supra2", "Toyota Supra")
    AddTextEntry("evoque", "Range Rover Evoque")
    AddTextEntry("focusrs", "Ford Focus 2017 RS")
    AddTextEntry("benson3", "Mercedes Benz Sprinter")
    AddTextEntry("cp9a", "Mitsubishi Evo VI")
    AddTextEntry("jeepg", "Jeep Gladiator")
    AddTextEntry("raptor150", "Ford Raptor")
    AddTextEntry("nissantitan17", "Nissan Titan")
    AddTextEntry("rmodmk7", "Volkswagen Golf MK7 Widebody")
    AddTextEntry("giuliagtam", "Alfa Romeo Giulia")
    AddTextEntry("rs52021", "Audi RS5 2021")
    AddTextEntry("e63w213", "Mercedes E63 AMG")
    AddTextEntry("22m5", "BMW M5")
    AddTextEntry("m2f22", "Bmw M2F22")
    AddTextEntry("rmodrs6", "Audi RS6 C8")
    AddTextEntry("rs7", "Audi RS7")
    AddTextEntry("m4lb", "Bmw M4 GT")
    AddTextEntry("bmwm8", "Bmw M8")
    AddTextEntry("mlmansory", "Maserati Levante")
    AddTextEntry("bmws", "Bmw S1000")
    AddTextEntry("rmodgt63", "Mercedes GT63S")
    AddTextEntry("skyline", "Nissan Skyline R34")
    AddTextEntry("q8prior", "Audi Q8 Prime Edition")
    AddTextEntry("r8spyder20", "Audi R8 Spyder")
    AddTextEntry("rmodx6", "Bmw X6")
    AddTextEntry("rmodx7", "Bmw X7")
    AddTextEntry("g63amg6x6", "Mercedes G63 6x6")
    AddTextEntry("g63m", "Mercedes G63 Mansory")
    AddTextEntry("19gt500", "Ford Mustang Shelby")
    AddTextEntry("urus", "Lamborghini Urus")
    AddTextEntry("tr22", "Tesla Roadster")
    AddTextEntry("rocket", "Rocket")
    AddTextEntry("gtr", "Nissan GTR")
    AddTextEntry("911turbos", "Porshe 911 TurboS")
    AddTextEntry("pistas", "Ferrari 488 Pista Spider")
    AddTextEntry("rmodmartin", "Aston Martin Superleggera")
    AddTextEntry("rmodlp750", "Lamborghini Aventador SVJ")
    AddTextEntry("18performante", "Lamborghini Huracan Performance")
    AddTextEntry("p1", "McLaren P1")
    AddTextEntry("divo", "Bugatti Divo")
    AddTextEntry("vulcan", "Aston Martin Vulcan")
    AddTextEntry("mi8", "BMW I8")
    AddTextEntry("sclgt63s", "Mercedes SCL Diamant GT63S")
    AddTextEntry("bdivo", "Bugatti Divo Prezmo")
    AddTextEntry("aperta", "Ferrari La Ferrari")
    AddTextEntry("roma20", "Ferrari Roma")
    AddTextEntry("h2carb", "Kawasaki H2")
    AddTextEntry("jes", "Koenigsegg Jesko")
    AddTextEntry("rmodskyline34", "Nissan Skyline R34")
    AddTextEntry("rmodveneno", "Lamborghini Veneno")
    AddTextEntry("pandemraptor", "Pandem Raptor")
    AddTextEntry("pgt3", "Porsche GT3")
    AddTextEntry("defenderoffp", "Range Rover Defender")
    AddTextEntry("812mnsry", "Ferrari 812 Mansory")
    AddTextEntry("sto", "Lamborghini STO")
    AddTextEntry("lamks", "Lamborghini Aventador KS AL")
    AddTextEntry("casup", "Toyota Supra MKV")
    AddTextEntry("brz", "Rocket Bunny V3 BRZ")
    AddTextEntry("bugvr", "Bugatti Veyron‘Grand Sport L'Or Blanc’")
    AddTextEntry("rmodsian", "Lamborghini Sian")
    AddTextEntry("rmodessenza", "Lamborghini Essenza SCV12")

    -- EXCLUSIVOS
    AddTextEntry("fd", "Mazda RX7")
    AddTextEntry("fxxk", "Ferrari FXXK")
    AddTextEntry("bmwhommage", "BMW Exclusivo")


    --INEM
    AddTextEntry("ambulancei", "INEM - Carrinha Volkswagen")
    AddTextEntry("anpc l200", "INEM - Carrinha Mitsubishi")
    AddTextEntry("emir vwgolf", "INEM - Volkswagen Golf")
    AddTextEntry("gt350r", "INEM - Carrinha Ford")
    AddTextEntry("ems gs1200", "INEM - Mota")
    AddTextEntry("pt inem4", "INEM - Ambulancia")
    AddTextEntry("heli1inem", "INEM - Heli")

    --- POLICIA DIAMOND
    AddTextEntry("Vra3", "Polícia - A3")
    AddTextEntry("Vra4", "Polícia - A4")
    AddTextEntry("Vrdm1200", "Polícia - Mota 1200")
    AddTextEntry("Vrq8", "Polícia - Q8")
    AddTextEntry("Vrraptor", "Polícia - Raptor")
    AddTextEntry("Vrrs5", "Polícia - RS5")
    AddTextEntry("Vrrs6", "Polícia - RS6")
    AddTextEntry("Vrrs6av", "Polícia - RS6AV")
    AddTextEntry("Vrtahoe", "Polícia - TAHOE")
    AddTextEntry("polmav", "Polícia - Heli")

    
    
    end)
    